### ISSUE TITLE
Create a deploy to Heroku Button

### ISSUE THREAD

**Issue by MaxJackson** [codehangar/goldenboy-bot#35]
generated by grailian

**Comment by grailian** [comment]
https://devcenter.heroku.com/articles/heroku-button

**Comment by grailian** [comment]
This is will need to be updated once #37 is completed, as some of the ENV configs won't be required any longer

**Comment by grailian** [comment]
Modify `app.json` to set `required: false` for the optional fields. 

See: https://devcenter.heroku.com/articles/app-json-schema
